const Map<String, Map<String, String>> appTexts = {
  'es': {
    'login': 'Iniciar sesión',
    'register': 'Registrarse',
    'email': 'Correo electrónico',
    'name': 'Nombre completo',
    'user': 'Usuario',
    'password': 'Contraseña',
    'no_account': '¿No tienes cuenta? Regístrate',
    'have_account': '¿Ya tienes cuenta? Inicia sesión',
    'change_theme': 'Cambiar tema',
    'change_language': 'Cambiar idioma',
    'settings': 'Ajustes',
    'home': 'Inicio',
    'control_home': 'Controla tu hogar',
    'subtitle_home': 'Puertas, ventanas y aire acondicionado',
    'air_conditioner': 'Aire acondicionado',
    'sprinklers': 'Regadores',
    'temperature_screen': 'Pantalla Temperatura',
    'doors': 'Puertas',
    'main_door': 'Puerta Principal',
    'garage_door': 'Puerta del Garaje',
    'windows': 'Ventanas',
    'living_window': 'Ventana Comedor',
    'bedroom1_window': 'Ventana Dormitorio 1',
    'bedroom2_window': 'Ventana Dormitorio 2',
    'open': 'Abierto',
    'closed': 'Cerrado',
    'account_data': 'Datos de cuenta',
    'account_data_sub': 'Ver o editar información de tu cuenta',
    'email_label': 'Correo electrónico:',
    'name_label': 'Nombre completo:',
    'user_label': 'Usuario:',
    'close': 'Cerrar',
    'connect_devices': 'Conectar dispositivos',
    'connect_devices_sub': 'Cámaras, sensores y más',
    'logout': 'Cerrar sesión',
    'logout_confirm': '¿Cerrar sesión?',
    'logout_question': '¿Estás seguro de que deseas cerrar la sesión?',
    'cancel': 'Cancelar',
    'register_success': '¡Registro exitoso! Ahora inicia sesión.',
    'fill_fields': 'Completa todos los campos',
    'wrong_user_pass': 'Usuario o contraseña incorrectos',
    'add_camera': 'Agregar cámara',
    'add_sensor': 'Agregar sensor',
    'coming_soon': 'Funcionalidad próximamente',
    'device_connection_title': 'Conectar dispositivos',
    'device_connection_subtitle': 'Conexión de cámaras y sensores',
    'device_connection_desc': 'Aquí podrás conectar y configurar tus cámaras, sensores y otros dispositivos inteligentes compatibles con NeuroHome.',
  },
  'en': {
    'login': 'Login',
    'register': 'Register',
    'email': 'Email',
    'name': 'Full name',
    'user': 'Username',
    'password': 'Password',
    'no_account': "Don't have an account? Register",
    'have_account': 'Already have an account? Login',
    'change_theme': 'Change theme',
    'change_language': 'Change language',
    'settings': 'Settings',
    'home': 'Home',
    'control_home': 'Control your home',
    'subtitle_home': 'Doors, windows and air conditioning',
    'air_conditioner': 'Air Conditioner',
    'sprinklers': 'Sprinklers',
    'temperature_screen': 'Temperature Screen',
    'doors': 'Doors',
    'main_door': 'Main Door',
    'garage_door': 'Garage Door',
    'windows': 'Windows',
    'living_window': 'Living Room Window',
    'bedroom1_window': 'Bedroom 1 Window',
    'bedroom2_window': 'Bedroom 2 Window',
    'open': 'Open',
    'closed': 'Closed',
    'account_data': 'Account Data',
    'account_data_sub': 'View or edit your account information',
    'email_label': 'Email:',
    'name_label': 'Full name:',
    'user_label': 'Username:',
    'close': 'Close',
    'connect_devices': 'Connect devices',
    'connect_devices_sub': 'Cameras, sensors and more',
    'logout': 'Logout',
    'logout_confirm': 'Logout?',
    'logout_question': 'Are you sure you want to logout?',
    'cancel': 'Cancel',
    'register_success': 'Registration successful! Now login.',
    'fill_fields': 'Complete all fields',
    'wrong_user_pass': 'Incorrect username or password',
    'add_camera': 'Add camera',
    'add_sensor': 'Add sensor',
    'coming_soon': 'Feature coming soon',
    'device_connection_title': 'Connect devices',
    'device_connection_subtitle': 'Camera and sensor connection',
    'device_connection_desc': 'Here you can connect and configure your cameras, sensors and other smart devices compatible with NeuroHome.',
  }
};

String t(String key, String locale) => appTexts[locale]?[key] ?? key;